- hosts: all
  remote_user: vagrant
  sudo: true
  vars:
    postgresql_version: 9.3
    postgresql_encoding: 'UTF-8'
    postgresql_locale: 'en_US.UTF-8'

    postgresql_admin_user: "postgres"
    postgresql_default_auth_method: "trust"

    postgresql_cluster_name: "main"
    postgresql_cluster_reset: false
  roles:
    - ANXS.postgresql