version: "2"
services:
  rb3:
    build: .
    ports:
      - "3100:3100"
      - "5001:5001"
    volumes:
      - .:/usr/src/funnelchat
    links:
      - db3
      - redis
      - bower_packages3
    # This tells the api container to mount 'gems' folder from 'bundle' image
    # to api containers /gems path
    volumes_from:
      - bundle3
      - node_modules3
      - bower_packages3

  redis:
    image: redis
    ports:
      - "6379:6379"

  db3:
    image: postgres

  bundle3:
    image: busybox
    volumes:
      - /gems

  node_modules3:
    image: busybox
    volumes:
      - /node_modules

  bower_packages3:
    image: busybox
    volumes:
      - /bower_packages