FROM ruby:2.3
MAINTAINER checkraiser11@gmail.com
RUN useradd -ou 0 -g 0 telegramd
RUN apt-get update && apt-get install -y \
    libreadline-dev\
    libconfig-dev\
    libssl-dev\
    lua5.2\
    liblua5.2-dev\
    libevent-dev\
    libjansson-dev\
    libpython-dev\
    make


RUN mkdir -p /root/funnelchat2
ENV APP_HOME /root/funnelchat2
RUN cd $APP_HOME && \
    git clone --recursive https://github.com/vysheng/tg.git && \
    cd tg && \
    pwd && \
    ./configure && \
    make

RUN cd $APP_HOME && \
    git clone https://github.com/checkraiser/telegram-rb.git && \
    cd telegram-rb && \
    bundle install && \
    gem build telegram-rb.gemspec && \
    gem install telegram-rb-0.1.0.gem

WORKDIR $APP_HOME
COPY ./telegram_control.rb $APP_HOME/
COPY ./telegram_daemon.rb $APP_HOME/
COPY ./start_telegram.sh $APP_HOME/
COPY ./config/tg_server.pub $APP_HOME/
ENV PATH $APP_HOME/tg/bin/:$PATH
RUN mkdir $HOME/.telegram-cli
#ADD ./.telegram-cli $HOME/
#RUN ls $HOME/.telegram-cli
RUN chown -R telegramd $HOME/.telegram-cli
#RUN $APP_HOME/tg/bin/telegram-cli -k $APP_HOME/tg_server.pub
RUN gem install daemons
RUN gem install redis
RUN gem install em-hiredis

CMD ["ls"]
